server:
    port: 8080
spring:
    application:
        name: seckill-demo
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: '***'
        url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
        username: '***'
    thymeleaf:
        cache: true
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
        excluded-view-names: ''
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
